---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: infoblox
    inherits: 
    description: 
  fields:
  - AcquireIPAddress:
      value: "/Integration/Infoblox/Operations/Methods/AcquireIPAddress#create"
  - ReleaseIPAddress:
      value: "/Integration/Infoblox/Operations/Methods/ReleaseIPAddress#create"
