---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - api_version:
      value: vX.x
  - password:
      value: v2:{wK1mFX68uddkEpp/n33WVA==}
  - server:
      value: infoblox.example.com
